import { defineSecret } from 'firebase-functions/params';

// Declared once, here, so both index.ts and any other module (e.g. screening/simulateTurn.ts)
// can import the SecretParam objects directly without a circular import through index.ts —
// index.ts itself imports several screening modules, so those modules importing secrets back
// from index.ts would create an import cycle where the secret bindings are still undefined
// at the time they're read (module evaluation order hazard).
export const anthropicKey = defineSecret('ANTHROPIC_API_KEY');
export const twilioAccountSid = defineSecret('TWILIO_ACCOUNT_SID');
export const twilioAuthToken = defineSecret('TWILIO_AUTH_TOKEN');
export const elevenLabsKey = defineSecret('ELEVENLABS_API_KEY');
// A shared bearer token, not a vendor credential -- generated by the executor (32 random
// hex bytes) and pasted into the ElevenLabs dashboard's Custom LLM "Add Secret" field, so
// elevenlabsCustomLlm.ts can verify inbound requests actually came from our own agent (T-02-05).
export const elevenLabsLlmToken = defineSecret('ELEVENLABS_LLM_TOKEN');
// Phase 4's VER-05 signed-link fallback -- a server-only HMAC key, distinct from the
// four vendor secrets above. See functions/src/verification/verifyLink.ts.
export const verifyLinkSecret = defineSecret('VERIFY_LINK_SECRET');
// Phase 5's DEMO-01 shared secret gating the destructive resetDemo onCall -- generated
// by the executor (openssl rand -hex 24) and set non-interactively, never a vendor
// credential. See functions/src/demo/resetDemo.ts.
export const demoToken = defineSecret('DEMO_TOKEN');
// Phase 5's ATK-01 attack simulator -- the second ("Attacker") ElevenLabs agent id and
// its imported outbound-caller-ID phone_number id, set via the ElevenLabs dashboard
// (see ATTACKER_CONSENT.md for the consented-clone process that precedes these values
// existing at all). See functions/src/attack/attackCall.ts.
export const elevenLabsAttackerAgentId = defineSecret('ELEVENLABS_ATTACKER_AGENT_ID');
export const elevenLabsAttackerPhoneId = defineSecret('ELEVENLABS_ATTACKER_PHONE_ID');
